export const ACTION_CONST = {
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  REMOVE_DATA: "REMOVE_DATA",
  FETCH_DATA_ERROR: "FETCH_DATA_ERROR",
  LOGGED_IN: "LOGGED_IN",
  FETCH_USERS: "FETCH_USERS",
  LOGGED_OUT: "LOGGED_OUT",
};
